#pragma once

#include "driver/gpio.h"

// Motor pins
#define PIN_MOTOR_A_IN1 GPIO_NUM_18
#define PIN_MOTOR_A_IN2 GPIO_NUM_5
#define PIN_MOTOR_B_IN1 GPIO_NUM_19
#define PIN_MOTOR_B_IN2 GPIO_NUM_21

// Sensor pins (ADC1 channels)
#define PIN_SENSOR_LEFT GPIO_NUM_33     // ADC1_CHANNEL_5
#define PIN_SENSOR_CENTER GPIO_NUM_35   // ADC1_CHANNEL_7
#define PIN_SENSOR_RIGHT GPIO_NUM_32    // ADC1_CHANNEL_4

// IO pins
#define PIN_LED_R GPIO_NUM_12
#define PIN_LED_G GPIO_NUM_14
#define PIN_LED_B GPIO_NUM_13
#define PIN_BUTTON GPIO_NUM_0
#define PIN_GO GPIO_NUM_4

// Control parameters
#define SENSOR_COUNT 3
#define LINE_POSITION_TARGET 50.0f
#define SENSOR_KEEP_TRACK_THRESHOLD 600
#define SENSOR_NOISE_THRESHOLD 600
#define SENSOR_POSITION_STEP 50
#define SENSOR_SPEED_BOOST_THRESHOLD 3000
#define SENSOR_SPEED_BOOST_DURATION_MS 1000

#define BASE_SPEED_DEFAULT 150.0f
#define BASE_SPEED_BOOST 250.0f

#define CONTROL_LOOP_DELAY_MS 10
#define KP_DEFAULT 1.5f
#define KD_DEFAULT 0.2f

